version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4203:4203"
      - "49153:49153"  # live-reload port
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/bower_components
    environment:
      - NODE_ENV=development
    command: npm start
    stdin_open: true
    tty: true